### ISSUE TITLE
Lets Encrypt second Domain

### ISSUE THREAD

**Issue by AlexanderSch90** [nextcloud/nextcloudpi#958] opened 2019-07-24 05:34 UTC
Is it possible to generate a SSL Script to a second Domain? Can it be integradet in the Web GUI?
Is it possible to integrad this manually as a quick sollution?

**Comment by feutl** [comment] 2019-09-03 11:03
Could this be a duplicate of https://github.com/nextcloud/nextcloudpi/issues/837

**Closed** 2019-09-03 11:07 UTC
Labels: duplicate, feature request
