### ISSUE TITLE
Request: Changelog visible in Nextcloudpi-config once new updates available

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#262] opened 2017-10-19 20:30 UTC
It'd be helpful to see a changelog of what has specifically changed every time a new Nextcloudpi-config update is released.  This would allow the admin to review the changelog from the cli or web interface before making the upgrade.

**Comment by nachoparker** [comment] 2017-10-20 09:29
Duplicate of #139

**Comment by nachoparker** [comment] 2017-10-20 09:29
Hi,

This was already implemented in #139. The autogenerated changelog is [here](https://github.com/nextcloud/nextcloudpi/issues/139)

There's a link in the wiki, and you can also click on the version number in ncp-web

**Closed by nachoparker** 2017-10-20 09:29 UTC
