### ISSUE TITLE
nc-scan browser freezes

### ISSUE THREAD

**Issue by Jeanoo** [nextcloud/nextcloudpi#1555] opened 2022-08-30 08:12 UTC
Hello,
When I did an nc-scan the browser freezes, and blocks the internet connection of the whole network.
I tested on firefox windows and unbutu 

`<html><body>

NextCloudPi version | v1.49.0
-- | --
OS | Raspbian GNU/Linux 10. 5.10.103-v7l+ (armv7l)
automount | yes
USB devices | sda sdb
datadir | /media/myCloudDrive/ncdata
data in SD | no
data filesystem | btrfs
data disk usage | 461G/1.9T
rootfs usage | 6.3G/15G
swapfile | /var/swap
dbdir | /var/lib/mysql
Nextcloud check | ok
Nextcloud version | 23.0.8.1
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
HPB service | up
Postfix service | up
internet check | ok
port check 80 | open
port check 443 | open
interface | eth0
certificates | data.*******.com
NAT loopback | no

</body>
</html>`

**Comment by Jeanoo** [comment] 2022-09-14 19:58
The scan works normally if it is done from an ssh terminal

**Comment by theCalcaholic** [comment] 2022-10-15 11:08
Unfortunately I can't reproduce this in any of my installations and have no idea 1) how this could happen and 2) how to attempt to troubleshoot this.
I'm therefore closing this issue, because I don't know how to approach it.

**Closed by theCalcaholic** 2022-10-15 11:08 UTC
Labels: has-updates
