### ISSUE TITLE
NextCloudPi Panel password

### ISSUE THREAD

**Issue by wildthing1** [nextcloud/nextcloudpi#413] opened 2018-02-14 10:01 UTC
In the NextCloudPi panel, tab "nc-passwd" it's not possible to set passwords that contain "!" (exclamation mark). Not a big issue though...

**Comment by theCalcaholic** [comment] 2018-02-14 12:16
This is currently not easily resolvable, due to the design of the ncp-web backend, but might get a fix if/when we start refactoring ncp-web.

**Comment by theCalcaholic** [comment] 2018-02-14 12:17
For documentation purposes: The problem is the regex testing of config values in ncp-launcher.php

**Comment by nachoparker** [comment] 2018-02-14 12:19
We need to carefully sanitize any input to prevent code injection. `!` means history expansion in bash and is really dangerous.

Whenever we refactor this this will be fixed, but it is not going to happen in the near future.

Thanks for reporting

**Closed by nachoparker** 2018-02-14 12:19 UTC
Labels: enhancement, ncp-web
