### ISSUE TITLE
UPnP port forwarding for coTURN

### ISSUE THREAD

**Issue by Mohammed-Al-Haidary** [nextcloud/nextcloudpi#1093] opened 2020-03-02 13:16 UTC
Hi,

Hope all is well. I would like to request a feature in the NextcloudPi panel where the user could forward the port for the coTURN server after installing it and NC Talk.
It would be just like the port forwarding feature for external access, but this time for the coTURN server port.
Perhaps it could be added as a new script or as an addition to the already existing port forwarding script in NCP panel, just by adding an additional field for coTURN.

Thank you in advance 👋 
Kind regards.

**Comment by nachoparker** [comment] 2020-03-03 01:36
Hi,

Thanks for participating.

Duplicate of #1068

**Closed by nachoparker** 2020-03-03 01:36 UTC
