### ISSUE TITLE
% used full

### ISSUE THREAD

**Issue by swr85260** [nextcloud/nextcloudpi#295] opened 2017-11-14 20:30 UTC
After new setup with fresh installation with the wizard, on a 180Go SSD I've got 91% full after only 400Mo
Enclosed 2 pictures with NCDATA location on the SSD with automount

![capture](https://user-images.githubusercontent.com/30535355/32803105-c427c51e-c982-11e7-9f56-3f94b9070409.JPG)
![capture2](https://user-images.githubusercontent.com/30535355/32803106-c48edbdc-c982-11e7-83cb-14a99145f7a6.JPG)

**Comment by sunjam** [comment] 2017-11-14 22:14
SSH into the Pi and `df -h /path/to/ssd` to confirm it is actually full.  My up-to-date 12.0.3 instance currently displays 0% used in the Nextcloud interface, which is also wrong.  Fyi, my database and ncdata are stored on a USB drive, as setup through NCP.  Once I moved them the % became 0%.

**Comment by nachoparker** [comment] 2017-11-15 07:04
there was an issue with the available space, but I think it got fixed in 12.0.3

https://github.com/nextcloud/server/issues/6022

try what @sunjam suggests.

Maybe when you move it to the USB drive NC doesn't get it right? we would have to confirm this

**Comment by nachoparker** [comment] 2017-11-15 18:16
> Once I moved them the % became 0%.

I didn't read that right... I guess it is confirmed then? using nc-datadir breaks the available space indicator... that would have to be reported to nextcloud/server

**Comment by swr85260** [comment] 2017-11-16 19:42
**sujam : "df -h"**

pi@nextcloudpi:/media/USBdrive $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.7G  2.5G  152K 100% /
devtmpfs        460M     0  460M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   13M  452M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
tmpfs           464M     0  464M   0% /tmp
tmpfs           464M  184K  464M   1% /var/log
/dev/mmcblk0p1   42M   21M   21M  51% /boot
/dev/sda1       165G   61M  156G   1% /media/myCloudDrive
tmpfs            93M     0   93M   0% /run/user/1000

**Natchopaker : "moving to NCDATADIR"**
/media/USBdrive/ncdata is not empty

**Comment by sunjam** [comment] 2017-11-16 22:44
@swr85260 Looks like ` /dev/sda1 165G 61M 156G 1% /media/myCloudDrive` is your external storage device.
    
Easiest fix would be to change the mount point for `/dev/sda1` from `/media/myCloudDrive` to `/media/USBdrive/` so it will show up as NextcloudPi is currently expecting.

**Comment by sunjam** [comment] 2017-11-16 22:52
@nachoparker my NextcloudPi instance only sees data that I'm pushing to the device by dropping directly into the web interface via drag and drop -- example is the two screenshots, totalling 38kb, that I drag and dropped into the files app from a browser showing up in the % full.  However, external photos I'm constantly uploading to the default USB data location are displayed in the files app as taking 37.8gb, but are not displayed in % storage used.
![screenshot_2017-11-16_14-45-46](https://user-images.githubusercontent.com/1787238/32920169-2cd75d1c-cadd-11e7-89c5-ed72370f34db.png)
![screenshot_2017-11-16_14-49-54](https://user-images.githubusercontent.com/1787238/32920325-b21e4742-cadd-11e7-8b01-c22f3d7c7ed5.png)

**Comment by nachoparker** [comment] 2017-11-17 09:16
@swr85260 try moving it to `/media/myCloudDrive/myncdata

@sunjam probably `/media/USBdrive` and `/media/myCloudDrive` are the same folder. NCP creates symlinks for easier autoconfiguration.

```
ls -l /media
drwxrwxrwx 29 root root 4096 Nov 17 08:30 myCloudDrive
lrwxrwxrwx  1 root root   16 Nov 10 17:20 USBdrive -> /media/myCloudDrive
```

**Comment by nachoparker** [comment] 2017-11-17 11:05
@sunjam you are using the 'external storage' app right? this is unrelated to the way ncp does things, which is having the whole data folder in USBdrive

**Comment by swr85260** [comment] 2017-11-17 12:37
I understand the wizard mount the USB storage to the wrong place on "/media/USBdrive/ncdata" instead of "/media/myCloudDrive"

Having said that, I messed up the image by trying to move NCdata to a new place and I'm completetly stuck.

**Comment by nachoparker** [comment] 2017-11-17 13:09
`/media/USBdrive` and `/media/myCloudDrive` are the same place, one is a symlink to the other. See

```
ls -l /media
```

in ncp-web, try using `nc-datadir` to move it to `/media/myCloudDrive/myncdata`

still don't see anything to be fixed

**Comment by swr85260** [comment] 2017-11-17 20:51
I did a fresch new installation and moved Ncdata to "/media/myCloudDrive/myncdata"
![capture1](https://user-images.githubusercontent.com/30535355/32968358-3ea0aee0-cbe1-11e7-9488-5e2cc659fa68.JPG)
And moved files 166Mb and already 25% of total space !
![capture](https://user-images.githubusercontent.com/30535355/32968354-3ae3434e-cbe1-11e7-92e0-c68fa03ec737.JPG)

**Comment by nachoparker** [comment] 2017-11-17 22:58
Do you have automount selected?

output of 

```
ls -l /media
```

and

```
df -h
```
?

**Comment by swr85260** [comment] 2017-11-18 07:09
**Automount selected**
![capture](https://user-images.githubusercontent.com/30535355/32977925-784768cc-cc37-11e7-9f0a-c62beefbb36b.JPG)


**pi@nextcloudpi:~ $ ls -l /media**
total 12
drwxr-xr-x 3 root root 4096 Nov 17 20:37 myCloudDrive
drwxr-xr-x 3 root root 4096 Nov 17 20:35 myCloudDrive1
drwxr-xr-x 3 root root 4096 Nov 17 20:36 USBdrive
lrwxrwxrwx 1 root root   20 Nov 17 20:50 USBdrive1 -> /media/myCloudDrive1


**pi@nextcloudpi:~ $ df -h**
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.7G  2.2G  304M  89% /
devtmpfs        460M     0  460M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   13M  452M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1   42M   21M   21M  51% /boot
/dev/sda1       165G   61M  156G   1% /media/myCloudDrive1
tmpfs            93M     0   93M   0% /run/user/1000
pi@nextcloudpi:~ $

**Comment by nachoparker** [comment] 2017-11-18 11:07
mmm automount is doing something weird for you.

For a quick fix, use nc-datadir to move it to something like `/media/myCloudDrive1/ncdatadir1`

To understand what's going on, let's try

```
systemctl status automount-links
```

```
ls /media/USBdrive
```

```
ls /media/myCloudDrive
```

**Comment by swr85260** [comment] 2017-11-18 12:32
**pi@nextcloudpi:~ $ systemctl status nc-automount-links**
● nc-automount-links.service - Monitor /media for mountpoints and create USBdriv
   Loaded: loaded (/usr/lib/systemd/system/nc-automount-links.service; enabled;
   Active: active (running) since Sat 2017-11-18 08:13:11 UTC; 4h 15min ago
 Main PID: 373 (nc-automount-li)
   CGroup: /system.slice/nc-automount-links.service
           ├─373 /bin/bash /usr/local/etc/nc-automount-links-mon
           ├─398 inotifywait --monitor --event create --event delete --format %f
           ├─399 grep --line-buffered ISDIR
           └─400 /bin/bash /usr/local/etc/nc-automount-links-mon

Nov 18 08:13:11 nextcloudpi systemd[1]: Started Monitor /media for mountpoints a
Nov 18 08:13:12 nextcloudpi nc-automount-links-mon[373]: Setting up watches.
Nov 18 08:13:12 nextcloudpi nc-automount-links-mon[373]: Watches established.
Nov 18 08:13:15 nextcloudpi nc-automount-links-mon[373]: myCloudDrive1 DELETE,IS
Nov 18 08:13:15 nextcloudpi nc-automount-links-mon[373]: myCloudDrive1 CREATE,IS
lines 1-15/15 (END)

**pi@nextcloudpi:~ $ ls /media/USBdrive**
ncdata

**pi@nextcloudpi:~ $ ls /media/myCloudDrive**
myncdata

So...what's up doctor?

**Comment by nachoparker** [comment] 2017-11-19 10:36
I am glad that it worked.

It's hard to tell why those folders were created in the first place. In any case, now nc-datadir refuses to move to the SD card, so we shouldn't be seeing this again, and if something weird comes up we will be able to detect it better.

**Closed by nachoparker** 2017-11-19 10:36 UTC
Labels: question
