### ISSUE TITLE
`Can't connect to local MySQL server through socket` when restarting rPi

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/nextcloudpi#1127] opened 2020-04-27 08:30 UTC
After restarting the raspberry, NextCloudPi usually has the following error:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)`. The server is not available then, but it's docker status is `Up`.

A `docker restart <nextcloudpi_container>` resolves the issue. Then it starts as expected. 

**System information**
Raspberry Pi4
NextCloudPi version: `v1.25.0`
Docker image: `NextCloudPi_docker_03-20-20` (armhf)

The volume is mounted (btw. data is stored on a external disk):
```
volumes:
      - /mnt/hdd1/ncData:/data
      - /etc/localtime:/etc/localtime:ro
```

### 2 questions
1. Any ideas why this could happen?
2. Shouldn't the container exit if it can't connect to the DB? Then my restart policy could handle the issue.

**Comment by ovpc** [comment] 2020-04-27 08:49
Looks like db is on external too and not mounted yet (fstab) when docker starts. Should use forum tho, Github is for development, discussing bugs and documentation only.

**Comment by hunhejj** [comment] 2020-04-27 09:58
Because of the mounted volume (see above) the db is probably on the external drive too, yes.

**Comment by hunhejj** [comment] 2020-04-27 09:59
Isn't it a bug that the container seems to be up although the DB was not started?

**Comment by ovpc** [comment] 2020-06-19 14:54
Closing this, no-one has reproduced this afaik.

**Comment by Coernel82** [comment] 2020-07-14 07:19
@hunhejj Is it a Rapsberry Pi 4 with **8 GB**? I get the suspicion that the
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
ineed is a bug and that this thread needs to be reopened. [This source](https://forum-raspberrypi.de/forum/thread/47927-rpi-4-8gb-inkompatibel-mit-nextcloud/) also indicates it should be a real problem - but for the 8 GB version only.

**Comment by hunhejj** [comment] 2020-07-14 07:31
I had the issue with a raspberry pi 4 with 4GB

**Comment by ovpc** [comment] 2020-07-14 07:32
Reopening an issue does not make it a bug.
Anyone else reproducing this ?  on rpi4-8Gb, its a docker container too, which add's another layer

**Comment by markgllin** [comment] 2020-07-14 23:09
I'm currently running into the same issue on RPi4-2GB in the docker container.

From `docker logs`:
```
2020-07-14 23:01:32 0 [Note] mysqld (mysqld 10.3.22-MariaDB-0+deb10u1) starting as process 106 ...
Starting Redis
Starting Cron
Starting Postfix
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)
Init done
```

my `docker-compose.yml`:
```
services:
  nextcloud:
    image: ownyourbits/nextcloudpi-armhf
    container_name: nextcloud
    volumes:
      - ncdata:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 81:80
      - 445:443
      - 4443:4443

volumes:
   ncdata:
     driver: local
     driver_opts:
       type: 'none'
       o: 'bind'
       device: '/mnt/docker/docker/data'
```
what's curious is that it ran successfully the first time i did a `docker-compose up -d`, correctly creating the bindmount where the db is stored. 

`ncp-report` didn't seem to capture anything 
```
root@11eed60a5e62:/# ncp-report
<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

will continue debugging and report back if i find anything

**Comment by Coernel82** [comment] 2020-07-16 13:57
OK, I do my best for a bug report:

# Steps to reproduce
After multiple tries using the NextcloudPi image without being able to connect via SSH (I have no micro-hdmi cable to check whats happening on the device) I decided to try the Debian-Script:

<details>
<summary>Installing image, firstboot and Nextcloudpi-Install-Script</summary>

1. Downloading Raspian OS Image and verify checksum 
2. Writing Raspberry Pi OS (32-bit) Lite 2020-05-27 to SanDisk Ultra 32GB HC I Class 10 SD-Card and verify using Etcher.
3. copy ssh and wpa_supplicant.conf to boot partition for ssh and wifi access
4. boot up Raspberry Pi 4B (8 GB version)
5. log in by SSH
6. ```sudo apt-get update && sudo apt-get upgrade```
7. ```curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | sudo bash``` Note: **sudo** bash!
</details>

<details>
<summary>Trying to set up NextcloudPi</summary>

1. Open 192.168.178.29 without Port in Chrome, ignoring SSL warning
2. click acitvate
3. Error message loop: ```NextCloudPi not yet initialized, trying again in a few secons...```
4. via ssh ```sudo ncp-config'''
5. start NextcloudPi update by clicking Yes
</details>

# Output from ncp-report
```sudo ncp-report```

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.18.0
distribution         Raspbian GNU/Linux 10 \n \l
automount            no
USB devices          none
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      2.3G/29G
rootfs usage         2.3G/29G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      down
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            wlan0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               1:37

```
</details>


<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:68
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(420): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(380): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(324): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(683): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(155): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(195): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(157): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(749): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\ServerContainer->query('OCP\\IDBConnecti...')
#11 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#12 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('DatabaseConnect...')
#13 /var/www/nextcloud/lib/private/Server.php(1666): OC\ServerContainer->query('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/Server.php(422): OC\Server->getDatabaseConnection()
#15 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#16 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\\Authenticati...')
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(70): OC\ServerContainer->query('OC\\Authenticati...', true)
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(100): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#19 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#20 /var/www/nextcloud/lib/private/ServerContainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...', true)
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(70): OC\ServerContainer->query('OC\\Authenticati...', true)
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(100): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#23 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#24 /var/www/nextcloud/lib/private/ServerContainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...', true)
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\ServerContainer->query('OC\\Authenticati...')
#26 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#27 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\\Authenticati...')
#28 /var/www/nextcloud/lib/private/Server.php(434): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\\User\\Session')
#31 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\ServerContainer->query('OC\\User\\Session')
#32 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#33 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('UserSession')
#34 /var/www/nextcloud/lib/private/Server.php(1542): OC\ServerContainer->query('UserSession')
#35 /var/www/nextcloud/lib/private/Server.php(802): OC\Server->getUserSession()
#36 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#37 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#38 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\ServerContainer->query('OC\\App\\AppManag...')
#39 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#40 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('AppManager')
#41 /var/www/nextcloud/lib/private/Server.php(1837): OC\ServerContainer->query('AppManager')
#42 /var/www/nextcloud/lib/private/legacy/app.php(347): OC\Server->getAppManager()
#43 /var/www/nextcloud/lib/private/legacy/app.php(114): OC_App::getEnabledApps()
#44 /var/www/nextcloud/lib/base.php(645): OC_App::loadApps(Array)
#45 /var/www/nextcloud/lib/base.php(1089): OC::init()
#46 /var/www/nextcloud/console.php(48): require_once('/var/www/nextcl...')
#47 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#48 {main}
```
</details>


<details>
<summary>HTTPd logs</summary>

```

[Thu Jul 16 14:01:05.879268 2020] [core:notice] [pid 8937:tid 3069559312] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 16 14:09:25.446541 2020] [mpm_event:notice] [pid 8937:tid 3069559312] AH00491: caught SIGTERM, shutting down
[Thu Jul 16 14:09:25.643387 2020] [mpm_event:notice] [pid 25488:tid 3069477392] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Jul 16 14:09:25.643501 2020] [core:notice] [pid 25488:tid 3069477392] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 16 14:16:14.244903 2020] [mpm_event:notice] [pid 25488:tid 3069477392] AH00493: SIGUSR1 received.  Doing graceful restart
AH00112: Warning: DocumentRoot [/var/www/ncp-web/] does not exist
[Thu Jul 16 14:16:14.266447 2020] [ssl:warn] [pid 25488:tid 3069477392] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 16 14:16:14.266647 2020] [ssl:error] [pid 25488:tid 3069477392] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 03A0494A7FDF879AA7178E55957F171CE9EC019E / notbefore: Jul 16 13:04:40 2020 GMT / notafter: Jul 14 13:04:40 2030 GMT]
[Thu Jul 16 14:16:14.266666 2020] [ssl:error] [pid 25488:tid 3069477392] AH02604: Unable to configure certificate localhost:443:0 for stapling
[Thu Jul 16 14:16:14.267658 2020] [mpm_event:notice] [pid 25488:tid 3069477392] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Jul 16 14:16:14.267678 2020] [core:notice] [pid 25488:tid 3069477392] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 16 14:53:49.869506 2020] [mpm_event:notice] [pid 25488:tid 3069477392] AH00493: SIGUSR1 received.  Doing graceful restart
[Thu Jul 16 14:53:49.894655 2020] [ssl:warn] [pid 25488:tid 3069477392] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 16 14:53:49.894872 2020] [ssl:error] [pid 25488:tid 3069477392] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 03A0494A7FDF879AA7178E55957F171CE9EC019E / notbefore: Jul 16 13:04:40 2020 GMT / notafter: Jul 14 13:04:40 2030 GMT]
[Thu Jul 16 14:53:49.894891 2020] [ssl:error] [pid 25488:tid 3069477392] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Thu Jul 16 14:53:49.895606 2020] [ssl:warn] [pid 25488:tid 3069477392] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 16 14:53:49.895784 2020] [ssl:error] [pid 25488:tid 3069477392] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 03A0494A7FDF879AA7178E55957F171CE9EC019E / notbefore: Jul 16 13:04:40 2020 GMT / notafter: Jul 14 13:04:40 2030 GMT]
[Thu Jul 16 14:53:49.895801 2020] [ssl:error] [pid 25488:tid 3069477392] AH02604: Unable to configure certificate localhost:443:0 for stapling
[Thu Jul 16 14:53:49.897081 2020] [mpm_event:notice] [pid 25488:tid 3069477392] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Jul 16 14:53:49.897109 2020] [core:notice] [pid 25488:tid 3069477392] AH00094: Command line: '/usr/sbin/apache2'

```
</details>


<details>
<summary>Database logs</summary>

```

Resource Limits:
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             61664                61664                processes
Max open files            16364                16364                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       61664                61664                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
Core pattern: core


```
</details>


<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"XOVkQGCtQysnxW4XhIzA","level":3,"time":"2020-07-16T13:15:09+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/base.php","line":651,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"/var/www/nextcloud/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/nextcloud/cron.php","line":42,"args":["/var/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/base.php","Line":282,"CustomMessage":"--"},"userAgent":"--","version":""}

```
</details>

**Comment by Coernel82** [comment] 2020-08-13 09:46
A user in the German Raspberry-Pi-Forum gave a hint which might solve the problem:
https://forum-raspberrypi.de/forum/thread/47927-rpi-4-8gb-inkompatibel-mit-nextcloudpi/?postID=444544#post444544

Basically what he describes is that there is to much memory being allocated thus he decreases the allocated memory.

Original **English** thread from the nextcloud forums: https://help.nextcloud.com/t/cannot-allocate-memory-for-bufferpool-mariadb-on-fresh-raspberry-pi-4-8gb/87067/6

The mentionied file `nc-limits.sh` can be found in `/usr/local/bin/ncp/CONFIG`

**Comment by nachoparker** [comment] 2020-08-13 23:32
looks similar to what we already fixed here

https://github.com/nextcloud/nextcloudpi/issues/1141

**Comment by nachoparker** [comment] 2020-08-13 23:32
looks similar to what we already fixed here

https://github.com/nextcloud/nextcloudpi/issues/1141

**Comment by nachoparker** [comment] 2020-08-30 23:43
can't reproduce here with the latest container

**Closed by nachoparker** 2020-08-30 23:43 UTC
Labels: use forums please this is not for  support

**Comment by crooowned** [comment] 2020-12-10 19:14
Having the same issue with the 8gb Version. Force recovery not working, tried reflashing multiple times. Happens after rebooting multiple times. "sudo reboot now" (Not force reboots by unplugging)
