### ISSUE TITLE
NCP docker: ncp upgrade from 1.15 to 1.16.6 failed. Apache in maintenance mode

### ISSUE THREAD

**Issue by Brshk1** [nextcloud/nextcloudpi#1001] opened 2019-09-15 07:26 UTC
<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.16.6
NextCloudPi image    NextCloudPi_docker_07-20-19
distribution         Debian GNU/Linux 10 \n \l
automount            no
USB devices          sda 
datadir              /data/nextcloud/data
data in SD           no
data filesystem      btrfs
data disk usage      42G/431G
rootfs usage         2.6G/16G
swapfile             /var/swap
dbdir                /data/database
Nextcloud check      ok
Nextcloud version    15.0.5.3
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               1day

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "11": "85.87.88.15",
            "1": "172.17.0.2",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "6": "durango48200.duckdns.org",
            "4": "durango48200.duckdns.org",
            "20": "192.168.1.100",
            "21": "192.168.1.13",
            "2": "durango48200.duckdns.org",
            "22": "192.168.1.141"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/durango48200.duckdns.org\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "maintenance": false
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Sun Sep 15 07:07:27.601556 2019] [authz_host:error] [pid 5260:tid 1700439072] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.602117 2019] [authz_host:error] [pid 5260:tid 1683653664] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.819588 2019] [authz_host:error] [pid 5260:tid 1683653664] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/defaults.svg failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.819597 2019] [authz_host:error] [pid 5260:tid 1893471264] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/toggle.svg failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.839550 2019] [authz_host:error] [pid 5260:tid 1683653664] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/reboot.svg failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.839550 2019] [authz_host:error] [pid 5260:tid 1893471264] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/poweroff.svg failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.869428 2019] [authz_host:error] [pid 5260:tid 1893471264] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/search.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.869428 2019] [authz_host:error] [pid 5260:tid 1683653664] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/nc-button.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.869471 2019] [authz_host:error] [pid 5260:tid 1700439072] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/dashboard.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.870597 2019] [authz_host:error] [pid 5260:tid 1700439072] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/settings-white.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.870616 2019] [authz_host:error] [pid 5260:tid 1893471264] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/defaults-white.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.887106 2019] [authz_host:error] [pid 5260:tid 1683653664] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/wizard.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.887995 2019] [authz_host:error] [pid 5260:tid 1893471264] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/files.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.891684 2019] [authz_host:error] [pid 5260:tid 1700439072] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/info-white.svg failed, reason: unable to get the remote host name, referer: https://192.168.1.13:4443/css/ncp.css
[Sun Sep 15 07:07:27.919988 2019] [authz_host:error] [pid 5260:tid 1700439072] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:27.970287 2019] [authz_host:error] [pid 5260:tid 1893471264] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:35.414887 2019] [authz_host:error] [pid 5260:tid 1683653664] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:36.417182 2019] [authz_host:error] [pid 5260:tid 1750795296] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:36.418014 2019] [authz_host:error] [pid 5260:tid 1717224480] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/download.svg failed, reason: unable to get the remote host name
[Sun Sep 15 07:07:36.418358 2019] [authz_host:error] [pid 5260:tid 1717224480] [client 192.168.1.141:50932] AH01753: access check of 'localhost' to /img/delete.svg failed, reason: unable to get the remote host name

```
</details>

<details>
<summary>Database logs</summary>

```

2019-09-15  7:03:46 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-09-15  7:03:46 0 [Note] InnoDB: 10.3.15 started; log sequence number 535384991; transaction id 5399659
2019-09-15  7:03:46 0 [Note] InnoDB: Loading buffer pool(s) from /data/database/ib_buffer_pool
2019-09-15  7:03:46 0 [Note] Plugin 'FEEDBACK' is disabled.
2019-09-15  7:03:46 0 [Note] Server socket created on IP: '127.0.0.1'.
2019-09-15  7:03:46 0 [Note] Reading of all Master_info entries succeded
2019-09-15  7:03:46 0 [Note] Added new Master_info '' to hash table
2019-09-15  7:03:46 0 [Note] mysqld: ready for connections.
Version: '10.3.15-MariaDB-1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2019-09-15  7:03:46 0 [Note] InnoDB: Buffer pool(s) load completed at 190915  7:03:46
2019-09-15  7:03:51 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2019-09-15  7:03:51 0 [Note] Event Scheduler: Purging the queue. 0 events
2019-09-15  7:03:51 0 [Note] InnoDB: FTS optimize thread exiting.
2019-09-15  7:03:51 0 [Note] InnoDB: Starting shutdown...
2019-09-15  7:03:51 0 [Note] InnoDB: Dumping buffer pool(s) to /data/database/ib_buffer_pool
2019-09-15  7:03:51 0 [Note] InnoDB: Buffer pool(s) dump completed at 190915  7:03:51
2019-09-15  7:03:52 0 [Note] InnoDB: Shutdown completed; log sequence number 535388877; transaction id 5399677
2019-09-15  7:03:52 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2019-09-15  7:03:52 0 [Note] mysqld: Shutdown complete


```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"XW4UIawRAAIAAD1YoswAAABE","level":2,"time":"2019-09-03T07:20:32+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UIawRAAIAAD1YoswAAABE","level":2,"time":"2019-09-03T07:20:36+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4ULKwRAAIAAD4mM@EAAACT","level":2,"time":"2019-09-03T07:20:41+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4ULKwRAAIAAD4mM@EAAACT","level":2,"time":"2019-09-03T07:20:46+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4URawRAAIAAD1Yos0AAABD","level":2,"time":"2019-09-03T07:21:06+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/.Contacts-Backup\/","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4URawRAAIAAD1Yos0AAABD","level":2,"time":"2019-09-03T07:21:10+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/.Contacts-Backup\/","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UTqwRAAIAAD4mM@IAAACV","level":2,"time":"2019-09-03T07:21:31+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-09-01_20-27-21.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UTqwRAAIAAD4mM@IAAACV","level":2,"time":"2019-09-03T07:21:36+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-09-01_20-27-21.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UgKwRAAIAAD4mM@MAAACQ","level":2,"time":"2019-09-03T07:22:05+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PUT","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-09-01_20-27-21.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UgKwRAAIAAD4mM@MAAACQ","level":2,"time":"2019-09-03T07:22:09+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PUT","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-09-01_20-27-21.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UoqwRAAIAAD4mM@QAAACY","level":2,"time":"2019-09-03T07:22:39+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UoqwRAAIAAD4mM@QAAACY","level":2,"time":"2019-09-03T07:22:44+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UxKwRAAIAAD4mM@UAAACP","level":2,"time":"2019-09-03T07:23:13+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-08-31_20-05-53.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UxKwRAAIAAD4mM@UAAACP","level":2,"time":"2019-09-03T07:23:17+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"HEAD","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-08-31_20-05-53.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UzKwRAAIAAD4mM@YAAACS","level":2,"time":"2019-09-03T07:23:21+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4UzKwRAAIAAD4mM@YAAACS","level":2,"time":"2019-09-03T07:23:25+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4U5qwRAAIAAD4mM@cAAACR","level":2,"time":"2019-09-03T07:23:47+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PUT","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-08-31_20-05-53.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4U5qwRAAIAAD4mM@cAAACR","level":2,"time":"2019-09-03T07:23:51+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"PUT","url":"\/remote.php\/webdav\/.Contacts-Backup\/2019-08-31_20-05-53.vcf","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4U7qwRAAIAAD4mM@gAAACX","level":2,"time":"2019-09-03T07:23:55+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}
{"reqId":"XW4U7qwRAAIAAD4mM@gAAACX","level":2,"time":"2019-09-03T07:24:00+00:00","remoteAddr":"150.241.255.34","user":"--","app":"core","method":"GET","url":"\/index.php\/204","message":"Login failed: 'jdaniel' (Remote IP: '150.241.255.34')","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.2","version":"15.0.5.3"}

```
</details>

Guess that ncp-report won't give much info. The thing is that I tried to update NCP (running in docker) to the latest version. For some reason, it failed. I reckon it can have been due to power outage problems with my raspberry.

Even though, the server was still running ok. Then I set up dnsmasq and redid the container to open port 53/udp. After that, both ncp panel and nextcloud responded with apache being in maintenance mode due to server capacity or whatever.

Checked apache logs in the container and found error:
No such file or directory: AH02454: FCGI: attempt to connect 
to Unix domain socket /run/php/php7.2-fpm.sock (*) failed

I noticed that /run/php/php7.3-fpm.sock does exist. Then, I changed the corresponding wrong reference in /etc/apache2/conf-enabled/php7.2-fpm.conf and voil-la, everythin working fine again.

Just in case someone hits the same problem, or it has to do with some bug in the latest version.

**Comment by nachoparker** [comment] 2019-10-08 05:09
Thanks for reporting. Duplicate of https://github.com/nextcloud/nextcloudpi/issues/1002

**Closed by nachoparker** 2019-10-08 05:09 UTC
