### ISSUE TITLE
nc-hdd-test fails with 'unknown USB bridge'

### ISSUE THREAD

**Issue by OlivierBondu** [nextcloud/nextcloudpi#731] opened 2018-12-04 13:05 UTC
Hi,

I'm running into trouble ... well, not really trouble, in fact, I'm running into nothing, with the new `nc-hdd-test`. The log of the check is pasted below :
```
[ nc-hdd-test ]

/dev/sda: Unknown USB bridge [0x059f:0x1010 (0xc683)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary

* Starting test on sda. Check results later

/dev/sda: Unknown USB bridge [0x059f:0x1010 (0xc683)]
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```
It seems that my USB hard drive is not recognized for some reason. Could you help me out ?

Also: many many thanks for the awesome job :smile: 

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v0.67.5
NextCloudPi image    NextCloudPi_03-18-18
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /media/USBdrive/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      133G/466G
rootfs usage         2.5G/15G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    14.0.4.2
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               55days

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "1": "192.168.1.10",
            "2": "192.168.1.10",
            "6": "***REMOVED SENSITIVE VALUE***",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "4": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/media\/USBdrive\/ncdata\/nextcloud.log",
        "theme": "",
        "loglevel": 0,
        "log_type": "file",
        "htaccess.RewriteBase": "\/"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Tue Dec 04 06:25:02.709557 2018] [ssl:warn] [pid 13179:tid 1995631888] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Dec 04 06:25:03.000520 2018] [mpm_event:notice] [pid 13179:tid 1995631888] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Tue Dec 04 06:25:03.000597 2018] [core:notice] [pid 13179:tid 1995631888] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 04 12:45:09.615270 2018] [proxy_fcgi:error] [pid 19366:tid 1708573728] [client 192.168.1.25:36820] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 41\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 43\nPHP message: NACHO auto\n - en\n\nPHP message: NACHO en\n - en\n\nPHP message: NACHO de\n - en\n\nPHP message: NACHO es\n - en\n\nPHP message: NACHO zh\n - en\n\n'
[Tue Dec 04 12:45:10.801150 2018] [proxy_fcgi:error] [pid 19366:tid 1700172832] [client 192.168.1.25:36820] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Tue Dec 04 12:46:25.160612 2018] [proxy_fcgi:error] [pid 19366:tid 1708573728] [client 192.168.1.25:36820] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 41\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 43\nPHP message: NACHO auto\n - en\n\nPHP message: NACHO en\n - en\n\nPHP message: NACHO de\n - en\n\nPHP message: NACHO es\n - en\n\nPHP message: NACHO zh\n - en\n\n'
[Tue Dec 04 12:46:26.134414 2018] [proxy_fcgi:error] [pid 19366:tid 1910055968] [client 192.168.1.25:36844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Tue Dec 04 12:46:30.535100 2018] [proxy_fcgi:error] [pid 19366:tid 1708573728] [client 192.168.1.25:36844] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 41\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 43\nPHP message: NACHO auto\n - en\n\nPHP message: NACHO en\n - en\n\nPHP message: NACHO de\n - en\n\nPHP message: NACHO es\n - en\n\nPHP message: NACHO zh\n - en\n\n'
[Tue Dec 04 12:46:31.503966 2018] [proxy_fcgi:error] [pid 19366:tid 1809343520] [client 192.168.1.25:36844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Tue Dec 04 12:49:54.307003 2018] [proxy_fcgi:error] [pid 19366:tid 1901663264] [client 192.168.1.25:36844] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 41\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/index.php on line 43\nPHP message: NACHO auto\n - en\n\nPHP message: NACHO en\n - en\n\nPHP message: NACHO de\n - en\n\nPHP message: NACHO es\n - en\n\nPHP message: NACHO zh\n - en\n\n'
[Tue Dec 04 12:49:55.294233 2018] [proxy_fcgi:error] [pid 19366:tid 1700172832] [client 192.168.1.25:36844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'

```
</details>

<details>
<summary>Database logs</summary>

```


```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"XAZ2f38AAQEAAEumjIIAAJYb","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026045 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026045)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2g38AAQEAAEumjIMAAJYh","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026047 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026047)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2f38AAQEAAEumjIIAAJYb","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026047 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026047)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2g38AAQEAAEumjIMAAJYh","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026048 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026048)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2g38AAQEAAEumjIMAAJYh","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"SCSSCacher: \/apps\/systemtags\/css\/systemtagsfilelist.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2f38AAQEAAEumjIIAAJYb","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026048 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026048)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2f38AAQEAAEumjIIAAJYb","level":0,"time":"2018-12-04T12:44:12+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"SCSSCacher: \/apps\/systemtags\/css\/systemtagsfilelist.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2n38AAQEAAEulKUkAABIJ","level":0,"time":"2018-12-04T12:44:15+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1","message":"No cache entry found for \/dummyuser\/files\/gallery.cnf (storage: home::dummyuser, internalPath: files\/gallery.cnf)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:24+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:24+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:24+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026050 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026050)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:24+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css.deps (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css.deps)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:24+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026051 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026051)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1025996 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1025996)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css.gzip (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/css\/settings\/4f30-e45a-settings.css.gzip)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026052 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026052)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026050 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026050)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026051 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026051)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"No cache entry found for \/appdata_ocyxuokvmjte\/preview\/1026052 (storage: local::\/media\/USBdrive\/ncdata\/, internalPath: appdata_ocyxuokvmjte\/preview\/1026052)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}
{"reqId":"XAZ2pn8AAQEAAEulKVAAAAMB","level":0,"time":"2018-12-04T12:44:27+00:00","remoteAddr":"192.168.1.254","user":"dummyuser","app":"core","method":"GET","url":"\/index.php\/settings\/user","message":"SCSSCacher: \/settings\/css\/settings.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/70.0.3538.77 Chrome\/70.0.3538.77 Safari\/537.36","version":"14.0.4.2"}

```
</details>

**Comment by nachoparker** [comment] 2018-12-05 00:10
probably a duplicate of https://github.com/nextcloud/nextcloudpi/issues/710 ?

**Closed by nachoparker** 2018-12-05 00:10 UTC
