### ISSUE TITLE
Errors in ncp-update to version 1.24.0

### ISSUE THREAD

**Issue by spencer2785** [nextcloud/nextcloudpi#1115] opened 2020-03-28 20:10 UTC
Hi,

I've tried to update to ncp 1.24.0 But I've got this Errors:

> Downloading updates
> Performing updates
> Update to buster available. Type 'sudo ncp-dist-upgrade' to upgrade
>                                                                                
> Broadcast message from ncp@nextcloudpi (pts/0) (Sat Mar 28 19:58:58 2020):     
>                                                                                
> Update to buster available. Type 'sudo ncp-dist-upgrade' to upgrade
>                                                                                
> ls: Zugriff auf '/etc/php/7.3/fpm/conf.d/*-opcache.ini' nicht möglich: Datei oder Verzeichnis nicht gefunden
> ls: Zugriff auf '/etc/php/7.3/cli/conf.d/*-opcache.ini' nicht möglich: Datei oder Verzeichnis nicht gefunden
> NextCloudPi updated to version v1.24.0
> 

Looks like there are some directories missing.

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.24.0
NextCloudPi image    NextCloudPi_10-05-18
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      3,7G/15G
rootfs usage         3,7G/15G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    18.0.2.2
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               8days

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "1": "192.168.178.5",
            "3": "ferlemann.ddns.net",
            "2": "raspberry.ferlemann.me",
            "4": "raspberry.ferlemann.me"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.2.2",
        "overwrite.cli.url": "https:\/\/raspberry.ferlemann.me\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "loglevel": "2",
        "log_type": "file",
        "maintenance": false,
        "jpeg_quality": "60",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "data-fingerprint": "5168a1f6495f64a972a88955bd83bcf0"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Sat Mar 28 19:56:06.965215 2020] [authz_host:error] [pid 13232:tid 1699689504] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:07.173776 2020] [authz_host:error] [pid 13232:tid 1682887712] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/defaults.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:07.174058 2020] [authz_host:error] [pid 13232:tid 1708090400] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/reboot.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:07.173776 2020] [authz_host:error] [pid 13232:tid 1716491296] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/poweroff.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:07.174600 2020] [authz_host:error] [pid 13232:tid 1691288608] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/toggle.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:07.174243 2020] [authz_host:error] [pid 13232:tid 1699689504] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.131193 2020] [authz_host:error] [pid 13232:tid 1716491296] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/search.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.131211 2020] [authz_host:error] [pid 13232:tid 1682887712] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/nc-button.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.131533 2020] [authz_host:error] [pid 13232:tid 1699689504] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.130900 2020] [authz_host:error] [pid 13232:tid 1708090400] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.131943 2020] [authz_host:error] [pid 13232:tid 1682887712] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/dashboard.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.130900 2020] [authz_host:error] [pid 13232:tid 1691288608] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.134270 2020] [authz_host:error] [pid 13232:tid 1682887712] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/settings-white.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.134341 2020] [authz_host:error] [pid 13232:tid 1708090400] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/defaults-white.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.134899 2020] [authz_host:error] [pid 13232:tid 1733293088] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/info-white.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.134929 2020] [authz_host:error] [pid 13232:tid 1724892192] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/wizard.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.138044 2020] [authz_host:error] [pid 13232:tid 1724892192] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/info.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:08.138587 2020] [authz_host:error] [pid 13232:tid 1716491296] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/files.svg failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:09.328762 2020] [authz_host:error] [pid 13232:tid 1716491296] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /img/favicon.png failed, reason: unable to get the remote host name
[Sat Mar 28 19:56:18.039520 2020] [authz_host:error] [pid 13232:tid 1691288608] [client 192.168.178.102:52871] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name

```
</details>

<details>
<summary>Database logs</summary>

```

2020-03-28 19:52:37 1996415120 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2020-03-28 19:52:37 1996415120 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2020-03-28 19:52:37 1996415120 [Note] InnoDB: The InnoDB memory heap is disabled
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-03-28 19:52:37 1996415120 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Compressed tables use zlib 1.2.8
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Using Linux native AIO
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Using generic crc32 instructions
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Completed initialization of buffer pool
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Highest supported file format is Barracuda.
2020-03-28 19:52:37 1996415120 [Note] InnoDB: 128 rollback segment(s) are active.
2020-03-28 19:52:37 1996415120 [Note] InnoDB: Waiting for purge to start
2020-03-28 19:52:37 1996415120 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.46-86.2 started; log sequence number 1799139392
2020-03-28 19:52:37 1384117040 [Note] InnoDB: Dumping buffer pool(s) not yet started
2020-03-28 19:52:37 1996415120 [Note] Plugin 'FEEDBACK' is disabled.
2020-03-28 19:52:37 1996415120 [Note] Server socket created on IP: '127.0.0.1'.
2020-03-28 19:52:37 1996415120 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.44-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.11

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"WJtgbQffBR7k2DYdDzRe","level":0,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Switches from deprecated \"production\" to \"stable\" update channel","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":0,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Sets the enterprise logo","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":0,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::info: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Repair step already executed","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":0,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Reset generated avatar flag","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:39:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:40:53+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"17.0.4.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:40:53+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"18.0.2.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:40:53+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"18.0.2.2"}
{"reqId":"WJtgbQffBR7k2DYdDzRe","level":1,"time":"2020-03-20T18:40:53+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"18.0.2.2"}
{"reqId":"lVLP4hzl5Tq5ZPm7fX34","level":2,"time":"2020-03-20T22:00:27+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 3661824 out of 4537507 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.2.2"}
{"reqId":"LYHmMc0mX5mvlPeWSa7A","level":2,"time":"2020-03-21T22:15:17+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 3948544 out of 4538955 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.2.2"}
{"reqId":"8RznsGRGXJKaulyR3pgP","level":2,"time":"2020-03-24T22:45:19+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 3932160 out of 4558844 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.2.2"}
{"reqId":"2EmM7XRVYTLQ8ykOkYN4","level":2,"time":"2020-03-25T23:00:14+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Connection timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.2.2"}
{"reqId":"t7TwRgzHWZCy5dAFEOsf","level":2,"time":"2020-03-26T23:00:28+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 671744 out of 4569920 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.2.2"}
{"reqId":"Xn@rpH8AAQEAADOwS7QAAAAV","level":2,"time":"2020-03-28T19:55:16+00:00","remoteAddr":"192.168.178.80","user":"--","app":"no app in context","method":"POST","url":"/index.php/login","message":"Login failed: admin (Remote IP: 192.168.178.80)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.2.2"}
{"reqId":"Xn@sBH8AAQEAADOx99kAAABW","level":2,"time":"2020-03-28T19:56:53+00:00","remoteAddr":"192.168.178.80","user":"--","app":"no app in context","method":"POST","url":"/index.php/login","message":"Login failed: admin (Remote IP: 192.168.178.80)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.2.2"}

```
</details>

**Comment by ovpc** [comment] 2020-06-19 15:28
not a bug, predates Buster,  no further input, so closing

**Closed by ovpc** 2020-06-19 15:28 UTC
