### ISSUE TITLE
Do not remove files from nextcloud/data on restore, if the backup does not contain data

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/nextcloudpi#1603] opened 2022-09-29 18:43 UTC
If I am not mistaken, ncp-restore removes all files from nextcloud/data, even if the backup restored does not contain any data.

IMHO, it should not do that, but leave the data folder alone. Restoring nextcloud because it is broken does not necessarily mean that the data should be removed. If the user does not know that, he might lose data unexpectedly.

**Comment by theCalcaholic** [comment] 2022-09-29 19:01
That's a duplicate of #1417  :)

**Closed by theCalcaholic** 2022-09-29 19:01 UTC
