### ISSUE TITLE
Cannot Load Zend OPcache - its already loaded

### ISSUE THREAD

**Issue by crossr1** [nextcloud/nextcloudpi#566] opened 2018-07-17 15:57 UTC
I have noticed with the release of v0.57.18 that I am seeing this error in multiple locations:

Cannot load Zend OPcache - it was already loaded

Thanks

**Comment by chiyi4488** [comment] 2018-07-19 13:45
I also have this problem when I run occ, but this does not affect my work.

**Comment by Iolaum** [comment] 2018-07-19 17:05
This is a duplicate of #416 
It was then fixed from @nachoparker with [this change](https://github.com/nextcloud/nextcloudpi/commit/4bdbf933ed0b809466e2f9e8b2552c40293d1ecd#diff-25e6ad8ebc5d26ba06d2bcb0b220149c)

And yes it is harmless- but it does fill /var/mail/www-data mailbox :o

**Comment by Iolaum** [comment] 2018-07-22 22:08
I removed the two relevant files (renamed one to keep as backup) but I am still getting the warning when I run `ncp-report`:

```
# pwd
/etc/php/7.0/fpm/conf.d
# ls -la | grep cache
lrwxrwxrwx 1 root root   39 Dec  4  2017 20-opcache.ini.bk -> /etc/php/7.0/mods-available/opcache.ini
```
Maybe I misunderstood the fix?

**Comment by nachoparker** [comment] 2018-07-22 22:10
maybe restart the service?

**Comment by Iolaum** [comment] 2018-07-22 22:31
Instead of restarting the services I reboot the ncp - Is that not achieving the same thing (apart from extra wasted computation)?

**Comment by nachoparker** [comment] 2018-07-22 22:32
yes, should be the same thing

**Comment by Iolaum** [comment] 2018-07-22 22:50
I managed to misconfigure opcache by removing both symlinks (#571) but this warning persisted (e.g. when typing `sudo ncp-report`)! So maybe there's another cause?

**Comment by nachoparker** [comment] 2018-07-22 22:52
maybe you forgot the `/etc/php/7.0/cli/conf.d/` folder?

**Comment by Iolaum** [comment] 2018-07-22 22:55
Correct!! dumb me :(

**Comment by nachoparker** [comment] 2018-07-22 23:02
awesome! this is an easy fix. Do you want to send a PR to devel?

**Comment by Iolaum** [comment] 2018-07-22 23:12
Yep, I ll send one. It's basically your code that I referenced earlier.

**Closed** 2018-07-23 00:14 UTC
