### ISSUE TITLE
Cannot upload from web client or desktop app

### ISSUE THREAD

**Issue by JohnAtl** [nextcloud/nextcloudpi#1569] opened 2022-09-24 17:24 UTC
Using NextCloudPi 1.49.0 or 1.50.0, I am unable to upload files from the web client or the desktop client.

I originally thought these locale errors were the issue, but after moving files to my external USB drive, the errors are back.

Rebooted, and it's working again.

#### locale errors
```
pi@nextcloudpi:~ $ sudo ncp-update
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Downloading updates
Performing updates
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
NextCloudPi updated to version v1.50.0
```

I did two things to fix this. I'm pretty sure the last command would be sufficient.
```
pi@nextcloudpi:~ $ sudo su -
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

root@nextcloudpi:~# echo "LC_ALL=en_US.UTF-8" >> /etc/environment
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen en_US.UTF-8
Generating locales (this might take a while)...
  en_GB.UTF-8... done
  en_US.UTF-8... done
Generation complete.
```

I also did this (not sure if previous commands were necessary).
```
pi@nextcloudpi:~ $ sudo dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
```

In the TUI for the above, I selected my locale, `en_US.UTF-8`.

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.50.0
NextCloudPi image    NextCloudPi_08-16-22
OS                   Debian GNU/Linux 11. 5.10.92-v8+ (aarch64)
automount            yes
USB devices          sda
datadir              /media/USBdrive/ncdata/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      3.6G/29G
rootfs usage         3.6G/29G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    24.0.3.2
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          up
Postfix service      up
Internet check       ok
public IP            ***REMOVED SENSITIVE VALUE***
public IP            ***REMOVED SENSITIVE VALUE***
Port check 80        closed
Port check 443       closed
IP                   ***REMOVED SENSITIVE VALUE***
Gateway              10.0.0.1
Interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
Uptime               54min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "7": "nextcloudpi",
            "5": "nextcloudpi.local",
            "8": "nextcloudpi.lan",
            "3": "nextcloudpi",
            "11": "73.54.228.53",
            "1": "10.0.0.4",
            "14": "nextcloudpi"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "https:\/\/nextcloudpi\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/USBdrive\/ncdata\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "logfile": "\/media\/USBdrive\/ncdata\/data\/nextcloud.log"
    }
}

```
</details>

Submission was too long, the full report is at [this gist](https://gist.github.com/JohnAtl/0517cee8087050fd6842b9c5021e8fae).

**Comment by theCalcaholic** [comment] 2022-10-15 11:13
@ZendaiOwl Could you please update the state of this issue (e.g. close it, assign a `bug`/`not a bug` label or assign yourself if you like)?

**Comment by ZendaiOwl** [comment] 2022-10-15 12:14
Closing this then, since we shouldn't configure a locale for the users, they should configure the one that's correct for them, in my opinion 🙏

**Closed** 2022-10-15 12:15 UTC
