### ISSUE TITLE
Ports are shown as closed where they are in fact open

### ISSUE THREAD

**Issue by Menneken** [nextcloud/nextcloudpi#1283] opened 2021-05-13 10:19 UTC
Hi, it seems I have a well known problem: NCP shows ports as closed where they are in fact open (as shown by portchecker.co). As a consequence, my installation is unable to refresh the Let´s Encrypt Certificate or do any updates.
My Installation:
<html><body>

NextCloudPi version | v1.34.7
-- | --
NextCloudPi image | NextCloudPi_12-20-19
distribution | Raspbian GNU/Linux 10 \n \l
automount | yes
USB devices | sda sdb sdc
datadir | /media/myCloudDrive/ncdata
data in SD | no
data filesystem | btrfs
data disk usage | 495G/932G
rootfs usage | 6.4G/59G
swapfile | /var/swap
dbdir | /var/lib/mysql/ncdatabase
Nextcloud check | ok
Nextcloud version | 20.0.4.0
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
Postfix service | up
internet check | no
port check 80 | closed
port check 443 | closed

</body>
</html>

**Comment by ovpc** [comment] 2021-05-13 10:24
Thought already fixed in v1.36.2 
https://github.com/nextcloud/nextcloudpi/releases/tag/v1.36.2

**Comment by stoneubi** [comment] 2021-05-13 11:54
Updated from 1.35 to 1.36.2 and ports are shown as closed. Worked before update and nextcloud instance is reachable from internet. So this information is missleading. 

![PortsClosed](https://user-images.githubusercontent.com/32926093/118122117-af556980-b3f2-11eb-94ca-2ed8debce23a.jpg)

System: Raspberry4 8 GB RAM, Dietpi as distro, Nextcloud 20.0.8

**Comment by nachoparker** [comment] 2021-05-13 14:32
There was a bug where they would show as open when they were actually closed.

Seems like the fix was incomplete, can't test right now since my ports are not open yet on my new ISP.

In any case, this is informational only, and does not affect Letsencrypt or anything else.

**Comment by nachoparker** [comment] 2021-05-13 14:36
I might have fixed, but can't test. Can someone please run `sudo ncp-update devel` and try again, see if it shows correctly now?

**Comment by ovpc** [comment] 2021-05-13 14:47
Nope still showing closed for me in develk v1.36.3

**Comment by nachoparker** [comment] 2021-05-13 16:01
ok, then I need someone who can debug this, since my ports are closed ATM

cc @dsmic

**Comment by vcbranco** [comment] 2021-05-13 16:07
version 1.36.3 showing closed here to

**Comment by vcbranco** [comment] 2021-05-13 17:27
I would like to help but I don't know how

**Comment by GNEUGNEUGNEU** [comment] 2021-05-24 20:23
i'm here to help too if needed

**Comment by nachoparker** [comment] 2021-05-25 01:58
If someone has the skills to fix this, please send a PR. Otherwise we'll have to wait until my ports are open.

**Comment by dsmic** [comment] 2021-05-25 04:50
Sorry I can not reproduce the problem. The version before your changes still works on my setup…

**Comment by Haraade** [comment] 2021-05-26 21:25
> Sorry I can not reproduce the problem. The version before your changes still works on my setup…

Worked, before the upgrade. This feature now creates false information for the user and is useless. A user of nextclod should know how to open router ports. Nextcloudpi fixes firewall (UFW) for required gates.

**Comment by suxlex** [comment] 2021-05-30 08:27
Before the change from 1.35.0 to 1.36.0 both ports were shown as open and now unfortunately as closed.

**Comment by nachoparker** [comment] 2021-06-02 19:48
Fixed in `v1.36.3`, thanks for the help!

**Closed by nachoparker** 2021-06-02 19:48 UTC
Labels: bug, ncp-web
