### ISSUE TITLE
Daily updates to Nextcloud 28.0.9 reported on NCP 1.55.1

### ISSUE THREAD

**Issue by Knubbel** [nextcloud/nextcloudpi#1979] opened 2024-09-18 18:02 UTC
**System information**
```
NextcloudPi version  v1.55.1
NextcloudPi image    NextCloudPi_RaspberryPi_v1.51.0.img
OS                   Debian GNU/Linux 11. 6.1.21-v8+ (aarch64)
automount            yes
USB devices          sda
datadir              /media/USB1/ncdata/data
data in SD           no
data filesystem      ext2/ext3
data disk usage      84G/939G
rootfs usage         6,4G/30G
swapfile             /var/swap
dbdir                /media/USBdrive/ncdatabase
Nextcloud check      ok
Nextcloud version    28.0.9.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          up
Postfix service      up
Internet check       ok
Public IPv4          ***REMOVED SENSITIVE VALUE***
Public IPv6          ***REMOVED SENSITIVE VALUE***
Port 80              [N/A]
Port 443             [N/A]
IP                   ***REMOVED SENSITIVE VALUE***
Gateway              ***REMOVED SENSITIVE VALUE***
Interface            eth0
Certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         yes
Uptime               39days
```

After NCP has autoupdated to v1.55.1 my NCP instance reports "Nextcloud was updated to 28.0.9" **every single morning**.
I do not know if actually a daily update somehow happens or if just the messaging is nuts.

Other than that the instance seems to be running normally.

NextCloudPi logs show the following entry:
```
[ nc-update-nc-apps-auto ]
checking for updates...
[ncp-update-nc]
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 876k 100 876k 0 0 2960k 0 --:--:-- --:--:-- --:--:-- 2960k
Could not find a valid upgrade path from '28.0.9' to ''. Nothing to update.
```
Later the message turned into:
```
[ncp-update-nc]
**Failed to reset failed state of unit ncp-encrypt.service: Unit ncp-encrypt.service not loaded.**
Running as unit: ncp-update-nc.service
**Nextcloud version 28.0.9 is already installed. Nothing to do.
Nextcloud update finished successfully.**
```

All this started on August 29th 2024.

At exactly this same time my auto backups stopped working.

```
Maintenance mode already enabled
backup database...
**mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table `oc_text_steps` at row: 3**
Abort...
```

**Comment by new-on-github** [comment] 2024-09-19 08:43
Same problem here.

**Comment by theCalcaholic** [comment] 2024-09-19 13:32
Thank you, I suspect that this is only an issue with the notifications (because your logs would be much larger if the update was actually performed daily).
I need to have a look at your issue with the auto backups though - likely a separate issue (with the latest NC version maybe), but might be more serious.

@new-on-github Do you experience the same issue with the auto backups by any chance?

**Comment by new-on-github** [comment] 2024-09-19 14:30
I recognized last week that a was on a old Nextcloud version, despite ncp-autoupdate-nc was turned on. While trying to manually update the Nextcloud version, the backup process also failed because the connection to the mysql database failed. The workaround was to change something in the config of the mysql-database. If I remember it correct, it was something like this:

```
[mysqld]
max_allowed_packet = 160M
net_read_timeout = 300
net_write_timeout = 600
innodb_buffer_pool_size = 2G

[mysqldump]
max_allowed_packet = 160M
```
Afterwards the backup worked and therefore the update to. But now I manually updated to 29.0.7 and cannot know, if the auto update is working, because this is the most recent Nextcloud version.


@theCalcaholic  Thanks for your work!

**Comment by new-on-github** [comment] 2024-09-19 18:08
> > the backup process also failed because the connection to the mysql database failed. The workaround was to change something in the config of the mysql-database. If I remember it correct, it was something like this:
> > ```
> > [mysqld]
> > max_allowed_packet = 160M
> > net_read_timeout = 300
> > net_write_timeout = 600
> > innodb_buffer_pool_size = 2G
> > 
> > [mysqldump]
> > max_allowed_packet = 160M
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Afterwards the backup worked and therefore the update to.
> 
> Can you tell me which config file this was and under which path? Maybe I could try this as well. I wonder, what causes this MySQL connection problem.

I added this to the mysql config file in 

`/etc/mysql/my.cnf`

**Comment by FadeFx** [comment] 2024-09-20 05:20
I have the same issue and I can not update it any further as when I try to I get an error message

ERROR 1045 (28000): Access denied for user ‘root’@‘localhost’

Looks like something with mariadb access

**Comment by FadeFx** [comment] 2024-09-20 22:13
> I have the same issue and I can not update it any further as when I try to I get an error message
> 
> ERROR 1045 (28000): Access denied for user ‘root’@‘localhost’
> 
> Looks like something with mariadb access

@theCalcaholic do u have any idea about this? Nectcloud is running normally and i can do backups in ncp. I am however a bit worried, that my backups may be dysfunctional due to this db access problem, althou they look correct.

**Comment by theCalcaholic** [comment] 2024-09-21 05:11
> I have the same issue and I can not update it any further as when I try to I get an error message
> 
> ERROR 1045 (28000): Access denied for user ‘root’@‘localhost’
> 
> Looks like something with mariadb access

That actually sounds like a separate issue. The original issue is related to timeouts when performing the database dump but doesn't have general issues with accessing the db.

Do I understand correctly that this only affects automatic backups, but manual backups from ncp-config still work?

**Comment by FadeFx** [comment] 2024-09-21 05:16
you are right, only the update process is affected. However, i am not yet sure it is related to the backup. any way to skip the backup in the update process for testing?

**Comment by FadeFx** [comment] 2024-09-21 05:24
[ nc-backup ] (Sat Sep 21 06:17:10 BST 2024)
Installing template 'ncp-metrics.cfg.sh'...
check free space...
clean up old backup /media/USBdrive/ncp-backups/nextcloud-bkp_20240901_1725156006.tar.gz
Maintenance mode enabled
backup database...
backup files...
backup /media/USBdrive/ncp-backups/nextcloud-bkp_20240921_1726895844.tar.gz generated
Maintenance mode disabled

**Comment by FadeFx** [comment] 2024-09-21 05:30
That is the full log of the update attempt



    [ nc-update-nextcloud ] (Sun Sep 15 08:57:28 BST 2024)
    Failed to reset failed state of unit ncp-encrypt.service: Unit ncp-encrypt.service not loaded.
    Running as unit: ncp-update-nc.service
    % Total % Received % Xferd Average Speed Time Time Time Current
    Dload Upload Total Spent Left Speed

    Current Nextcloud version 28.0.9
    Requested Nextcloud version latest
    Selected Nextcloud version 28.0.10
    INFO: You have requested an update to ‘latest’, but a direct update to ‘latest’ cannot be performed, so the latest available version that can be updated to (28.0.10) has been selected automatically.
    ERROR 1045 (28000): Access denied for user ‘root’@‘localhost’ (using password: NO)
    Nextcloud update finished successfully.

**Comment by FadeFx** [comment] 2024-09-21 05:32
Probably the (using password: NO) part is key here?

**Comment by schoetju** [comment] 2024-09-21 10:53
As an FYI: I faced mysql issues during nc-restore (as described in [forum](https://help.nextcloud.com/t/update-to-29-0-4-via-ncp-1-55-nc-update-nextcloud-failed/203280/5?u=schoetju)
Solution in my case: Start nc-limits to create/update mysql configuration.

**Comment by dwprod38** [comment] 2024-09-23 05:24
me bug with daily updated version 28.0.10 message... How to solve it ?

![image](https://github.com/user-attachments/assets/53cdaa79-b5ba-4099-b538-ad1349deea21)

**Comment by theCalcaholic** [comment] 2024-09-24 19:24
Fixed in v1.55.2

**Closed by theCalcaholic** 2024-09-24 19:24 UTC
Labels: bug

**Comment by FadeFx** [comment] 2024-09-24 20:07
Seems the mysql issue is present on another place in this was well...

```
 [ nc-update ] (Tue Sep 24 21:01:42 BST 2024)
Downloading updates
Performing updates
Running nc-autoupdate-nc
[ nc-autoupdate-nc ] (Tue Sep 24 21:03:33 BST 2024)
automatic Nextcloud updates enabled
automatic Nextcloud updates enabled

Installing template 'mysql/91-ncp.cnf.sh'...
Reloading MariaDB database server: mariadbd/usr/bin/mariadb-admin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
Error while applying update 1.55.2. Exiting...
```
Is there a manual way to update to 1.55.2?

**Comment by theCalcaholic** [comment] 2024-09-24 20:21
@FadeFx Yes, you can just run `ncp-update`

However, I doubt that your issue specifically will be fixed because it is a separate problem (and I honestly don't really know where to start looking for the cause atm)

**Comment by FadeFx** [comment] 2024-09-24 20:24
> @FadeFx Yes, you can just run `ncp-update`
> 
> However, I doubt that your issue specifically will be fixed because it is a separate problem (and I honestly don't really know where to start looking for the cause atm)

so your suggestion would also be to run nc-limits to reset DB config and then restore a backup?

**Comment by FadeFx** [comment] 2024-09-24 21:09
i have 'fixed' my issue now by resetting the root password of the database to empty using this manual: https://www.digitalocean.com/community/tutorials/how-to-reset-your-mysql-or-mariadb-root-password , changing this also in .my.cnf and in nextcloud config, now i am able to update. however, i think it is not good practice to have a open mysql database. is it somewhere possible to configure ncp to use a password for the root user? i thought it actually uses the password in .my.cnf

**Comment by theCalcaholic** [comment] 2024-09-24 22:10
> i have 'fixed' my issue now by resetting the root password of the database to empty using this manual: https://www.digitalocean.com/community/tutorials/how-to-reset-your-mysql-or-mariadb-root-password , changing this also in .my.cnf and in nextcloud config, now i am able to update. however, i think it is not good practice to have a open mysql database. is it somewhere possible to configure ncp to use a password for the root user? i thought it actually uses the password in .my.cnf

That's correct, NCP uses the password in /root/.my.cnf

**Comment by FadeFx** [comment] 2024-09-24 22:49
Strange, that one had been correct as well...

**Comment by FadeFx** [comment] 2024-09-25 17:20
does it have to be 

>password='mypassword'
or
>password=mypassword
?
