### ISSUE TITLE
Ownyourbits Down

### ISSUE THREAD

**Issue by feutl** [nextcloud/nextcloudpi#1053] opened 2020-01-13 19:21 UTC
Domain expired, it happened again https://github.com/nextcloud/nextcloudpi/issues/206

```
Domain Name: OWNYOURBITS. COM
Registry Domain ID: 2089651605_DOMAIN_COM-VRSN
Updated Date: 2020-01-13T08:47:03Z
Creation Date: 2017-01-12T20:22:07Z
Registry Expiry Date: 2021-01-12T20:22:07Z
```

And yes, the forum got used for this, but no answer so far
https://help.nextcloud.com/t/is-ownyourbits-com-website-down-or-expired/68000

**Comment by ovpc** [comment] 2020-01-14 06:10
Thanks for reporting. fixed now it seems.

**Closed by ovpc** 2020-01-14 06:10 UTC

**Comment by feutl** [comment] 2020-01-14 07:24
still down at least for me, so re-open the ticket until more than just one person reports it is fixed.
wohis tells me that the domain was renewed, but this is just not enough ;)

@ovpc  have you tested it ?

**Comment by ovpc** [comment] 2020-01-14 07:38
It has been reported on NCP telegram group to work again by several members, and 
![OwnYourBitsDNScheckScreenshot2020-01-14_08-29-53](https://user-images.githubusercontent.com/8775469/72323089-2916ff00-36a8-11ea-8d8d-26e5c58b62ee.png)
Loads fine here, DNS check is without errors.
Maybe should clear browser cash, or your DNS is slow and hasn't picked it up yet?

**Comment by coreybruce** [comment] 2022-07-22 04:37
domain is completely down

**Comment by theCalcaholic** [comment] 2022-07-22 20:37
The site is available again.  If it isn't working for you, please verify that the same is true for a different browser (and ideally, device) as well. It could be a caching issue on your client

**Comment by coreybruce** [comment] 2022-07-23 05:52
> The site is available again. If it isn't working for you, please verify that the same is true for a different browser (and ideally, device) as well. It could be a caching issue on your client

Not working for me, I tried it on my phone as well as my PC and it's down. I also tried a is it down website when I made this report and today and it still says it's down, I can't even ping the website..

![image](https://user-images.githubusercontent.com/8393780/180592259-2db0f65d-bf61-41c3-acdd-45eca8d025f1.png)

![image](https://user-images.githubusercontent.com/8393780/180592261-4b00b4e2-664a-467d-b6b2-e263076a7831.png)
![Screenshot_2022-07-23-15-45-45-62_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/8393780/180592410-83a788e5-6473-4e7d-9c90-1ba2cb0f881d.jpg)
![Screenshot_2022-07-23-15-46-34-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/8393780/180592414-63d17935-e6b8-4fe7-8b55-a9c853c09b17.jpg)


What has happened to this project? it use to work than the website went down and it's hard to find the working image for the raspberry pi and I've had issues with the image I did have for the pi 4 breaking

**Comment by theCalcaholic** [comment] 2022-07-23 13:51
@coreybruce Hi, the official page of NextcloudPi is https://nextcloudpi.com. (not linked to ownyourbits.com) It should be available.

In regard to your question: I recently took over project maintainership from Nacho and we started migrating all the hosting related things from his servers to other solutions. In the meanwhile, some things weren't available, but everything should now slowly fall into place.

The official page is https://nextcloudpi.com
The Wiki can be found at https://docs.nextcloudpi.com
Images can be found at https://github.com/nextcloud/nextcloudpi/releases

Sorry for any confusion that was caused by the migration

**Comment by coreybruce** [comment] 2022-07-23 16:19
Ahh right I see, thank you for informing me @theCalcaholic, is there a latest stable version of nextcloud pi or only v1.47.2-rc currently? :smile:

**Comment by theCalcaholic** [comment] 2022-07-23 17:23
> Ahh right I see, thank you for informing me @theCalcaholic, is there a latest stable version of nextcloud pi or only v1.47.2-rc currently @theCalcaholic ? :smile:  

Currently, 1.47.2-rc is the way to go. I'm working on the 1.48.2 image atm. :)

But 1.47.2 is confirmed working and will update to 1.48 with `ncp-update`

**Comment by coreybruce** [comment] 2022-07-24 01:16
Ok thanks,  I'll give it a go :smile:
