### ISSUE TITLE
Lets Encrypt renewal fails after moving to current Docker image

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1479] opened 2022-05-15 21:52 UTC
Pulled nextcloudpi:latest
Import ncp-config
Re-enable DNS
Re-enable webui
Updating ncp fails #1478 
Static IP and Domain are correctly listed under Trusted Domains
Port forwarding is properly setup, but incorrectly listed as closed with `nc-info` #1475 
Trusted Domain and IP lead to
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

ncp-report in next post

**Comment by sunjam** [comment] 2022-05-15 23:47
Related to #673 
Used apt-get in docker to add systemctl and full-upgrade

`systemctl status mysqld`
```
# systemctl status mariadb
mariadb.service - MariaDB 10.5.15 database server
    Loaded: loaded (/lib/systemd/system/mariadb.service, enabled)
    Active: failed (dead)
root@321d749b679d:/# systemctl status mysqld
mysqld.service - MariaDB 10.5.15 database server
    Loaded: loaded (/lib/systemd/system/mysqld.service, disabled)
    Active: inactive (dead)
```

**Comment by theCalcaholic** [comment] 2022-07-28 06:18
@sunjam Since this issue is 2 months old, I suppose you don't have that container anymore (or found a solution)?

**Comment by theCalcaholic** [comment] 2022-08-14 22:32
I'm closing the issue for now. Feel free to respond and I'll reopen it :)

**Comment by sunjam** [comment] 2022-08-17 18:12
I did not find a solution.  Got no response on the forum or anywhere else.  I still have the container.  Any suggestions?

**Comment by theCalcaholic** [comment] 2022-08-17 22:28
What exactly is the issue at this point? That mysql is not running? Or that the letsencrypt certificates are not renewed automatically?

Does a simple `service mysql start` do anything?

**Comment by sunjam** [comment] 2022-08-18 21:02
Tried `systemctl start mysql` but it does nothing within the docker container.  Also, systemctl is not included within the container.

**Comment by ZendaiOwl** [comment] 2022-08-19 09:22
Mm you're right, `systemd` with `systemctl` isn't in the container, when I've been experimenting with building the docker containers I had to add "systemd" to be installed inside the base container for that to work 🙏

**Comment by theCalcaholic** [comment] 2022-08-20 14:36
@sunjam Yes, that's why I was suggesting to run `service mysql start` :)

**Comment by theCalcaholic** [comment] 2022-08-20 14:37
> I had to add "systemd" to be installed inside the base container
@ZendaiOwl Please don't do that outside of experimentation, though. Systemd doesn't work reliably inside docker

**Comment by ZendaiOwl** [comment] 2022-08-20 14:41
> > I had to add "systemd" to be installed inside the base container
> @ZendaiOwl Please don't do that outside of experimentation, though. Systemd doesn't work reliably inside docker

Alright 🙏 I didn't know that, do you know why that is?

**Comment by theCalcaholic** [comment] 2022-08-20 14:47
It's just not designed for that. Docker is meant to be a containerization for single processes (we're abusing it a bit in that regard) and a process management engine like systemd is meant for the opposite of the spectrum :)

Apparently, [it's not impossible to do anymore](https://developers.redhat.com/blog/2019/04/24/how-to-run-systemd-in-a-container) (some time ago you needed host system access in order to run systemd, but it's not a very good idea for production still. That's why we use a very simple bash script for process management.

**Comment by ZendaiOwl** [comment] 2022-08-20 15:05
@theCalcaholic 
Alright, yeah I found an article about this from someone working with container runtimes at red hat 🥳 

Seems podman was developed to resolve such issues, he also outlines some of the problems with using systemd on a docker container without properly setting it up, if I understood it correctly 🙏

https://developers.redhat.com/blog/2019/04/24/how-to-run-systemd-in-a-container#other_cool_features_about_podman_and_systemd

**Comment by theCalcaholic** [comment] 2022-08-26 13:19
@sunjam Are you still interested in fixing this? I'm still curious about the output of `service mysql start` :)

> @sunjam Yes, that's why I was suggesting to run `service mysql start` :)

**Comment by ZendaiOwl** [comment] 2022-09-26 01:07
This issue can be closed, it is caused by the internal upgrade within docker, which should not be done unless the image you're pulling from has gone through precisely & exactly the same upgrade process as you did within your container, including configurations, package installation and all. 

And if anyone comes here reading, you can use systemd within a container, it is not recommended to use with docker directly however and you should use podman for that, which was developed by red hat to resolve the issues of using systemd within a container more easily. As can be read in the article linked in one of the comments above

**Closed by ZendaiOwl** 2022-09-26 01:07 UTC
Labels: bug, docker
