### ISSUE TITLE
Feature-Request: Disable Format-Option and enable Password-Protection in WebPanel 

### ISSUE THREAD

**Issue by steinhmor** [nextcloud/nextcloudpi#152] opened 2017-08-23 23:43 UTC
Hi, is there any easy way to prevent someone who has access to my network from formating the hdd via the web-panel? it would be greate to have the ability to disable some features in the webpanel (via ssh) and protect the webpanel with a login.
greetings and thanks for your great work!
Moritz

**Comment by nachoparker** [comment] 2017-08-24 03:55
Hi,

Thanks for the suggestions.

I know, that's a very important future that I want to start working on soon.

It's already in the roadmap, so I'll mark as duplicate of #132 and we can continue the discussion over there ;)

**Closed by nachoparker** 2017-08-24 03:55 UTC
Labels: duplicate, feature request

**Comment by nachoparker** [comment] 2017-09-05 07:38
Duplicate of #132
