### ISSUE TITLE
Docker Image 1.50.3 not available

### ISSUE THREAD

**Issue by BstAA** [nextcloud/nextcloudpi#1637] opened 2022-10-15 09:49 UTC
**System information**

* As of today the "latest" Docker image is version 1.50.2
* When just starting ncp-config within a 1.50.2 container it automatically suggests an update to v1.50.3

Klaus

**Comment by theCalcaholic** [comment] 2022-10-15 10:23
Thank you for the report. That is actually caused by an issue with the release pipeline, that I'm currently working on. However, it's not a big concern as this issue does not bring changes to docker containers.

I'll leave this issue open for users to find

**Comment by theCalcaholic** [comment] 2023-01-21 18:05
Closing, as v1.50.3 has since been superseeded by v1.50.5

**Closed by theCalcaholic** 2023-01-21 18:05 UTC
Labels: bug, docker, cicd, has-updates
