### ISSUE TITLE
Since latest Update, new Docker Instances do not finish initializing

### ISSUE THREAD

**Issue by timethy96** [nextcloud/nextcloudpi#1250] opened 2021-01-27 08:10 UTC
Hey hi hello from Germany and thank you a lot for the excellent work on this project.

For the past few days I spent hours and hours trying to find out, why my new Docker Containers of NCP suddenly do not initialize correctly anymore.

**Stuck on white screen with "Initializing NextcloudPi for the first time..." but with backend working and *Init done* in the logs**

I was experimenting around, so I was sure, that the problem came from there. It was only after trying out a lot of different things (changing sd-cards and power-supplies) and reading through every post I found, that I tried **rolling back** to an earlier version I still had (**v1.32.0**). Here no problems with the Init at all. Only that the now fixed bug with the data dir assigned to /data-ro/ was still there... (From there I can upgrade to the latest Version (**v1.34.6**) without loosing the functionality and manually change the datadir in the Nextcloud config.php)
From that I presume that there is a bug in the updates from the last few days.

**System information**

After getting it to work, I quickly set it back up to reproduce the steps to the bug and get a log to post here. I apologize for any inconsistencies in the logs due to the short running time.

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.34.6
NextCloudPi image    NextCloudPi_docker_01-19-21
distribution         Debian GNU/Linux 10 \n \l
automount            no
USB devices          sda 
datadir              /data/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      1.9G/116G
rootfs usage         1.9G/116G
swapfile             /dev/zram0
dbdir                /data/database
Nextcloud check      ok
Nextcloud version    18.0.3.0
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        closed
port check 443       closed
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               9:14

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "1": "172.17.0.2",
            "6": "192.168.0.108"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Wed Jan 27 08:05:26.180369 2021] [ssl:error] [pid 101:tid 548356236656] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=localhost / issuer: CN=localhost / serial: 5285EFBE66BF712AEC0DE78450C9537C14A3F5C3 / notbefore: Apr  6 07:00:05 2020 GMT / notafter: Apr  4 07:00:05 2030 GMT]
[Wed Jan 27 08:05:26.180404 2021] [ssl:error] [pid 101:tid 548356236656] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Wed Jan 27 08:05:26.181786 2021] [mpm_event:notice] [pid 101:tid 548356236656] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Jan 27 08:05:26.181815 2021] [core:notice] [pid 101:tid 548356236656] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 27 08:05:29.027153 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:30.979100 2021] [authnz_external:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AuthExtern pwauth [/usr/sbin/pwauth]: Failed (1) for user ncp
[Wed Jan 27 08:05:30.979314 2021] [auth_basic:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01617: user ncp: authentication failure for "/": Password Mismatch
[Wed Jan 27 08:05:33.951241 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.000949 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.001402 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.045923 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.264292 2021] [authz_host:error] [pid 1385:tid 548133474704] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /js/ncp.js failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.265793 2021] [authz_host:error] [pid 1385:tid 548041073040] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.266443 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /js/minified.js failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.266735 2021] [authz_host:error] [pid 1385:tid 548125082000] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.266864 2021] [authz_host:error] [pid 1385:tid 548049473936] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.843709 2021] [authz_host:error] [pid 1385:tid 548041073040] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:34.855338 2021] [authz_host:error] [pid 1385:tid 548141867408] [client 192.168.0.129:64434] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:43.556750 2021] [authz_host:error] [pid 1318:tid 548049473936] [client 192.168.0.129:64471] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Wed Jan 27 08:05:44.537897 2021] [authz_host:error] [pid 1318:tid 548049473936] [client 192.168.0.129:64471] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name

```
</details>

<details>
<summary>Database logs</summary>

```

2021-01-27  8:03:14 0 [ERROR] mysqld: Table './mysql/user' is marked as crashed and should be repaired
2021-01-27  8:03:14 0 [Warning] Checking table:   './mysql/user'
2021-01-27  8:03:14 0 [ERROR] mysql.user: 1 client is using or hasn't closed the table properly
2021-01-27  8:03:14 0 [ERROR] mysqld: Table './mysql/db' is marked as crashed and should be repaired
2021-01-27  8:03:14 0 [Warning] Checking table:   './mysql/db'
2021-01-27  8:03:14 0 [ERROR] mysql.db: 1 client is using or hasn't closed the table properly
2021-01-27  8:03:14 0 [Note] Reading of all Master_info entries succeeded
2021-01-27  8:03:14 0 [Note] Added new Master_info '' to hash table
2021-01-27  8:03:14 0 [Note] mysqld: ready for connections.
Version: '10.3.22-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2021-01-27  8:03:20 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2021-01-27  8:03:20 0 [Note] Event Scheduler: Purging the queue. 0 events
2021-01-27  8:03:20 0 [Note] InnoDB: FTS optimize thread exiting.
2021-01-27  8:03:21 0 [Note] InnoDB: Starting shutdown...
2021-01-27  8:03:21 0 [Note] InnoDB: Dumping buffer pool(s) to /data/database/ib_buffer_pool
2021-01-27  8:03:21 0 [Note] InnoDB: Buffer pool(s) dump completed at 210127  8:03:21
2021-01-27  8:03:22 0 [Note] InnoDB: Shutdown completed; log sequence number 4297011; transaction id 2780
2021-01-27  8:03:22 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-01-27  8:03:22 0 [Note] mysqld: Shutdown complete


```
</details>

<details>
<summary>Nextcloud logs</summary>

```


```
</details>

**Comment by timethy96** [comment] 2021-01-27 08:16
@ovpc I got it working, so no support requested.

**Comment by ovpc** [comment] 2021-01-27 08:19
Sorry, thanks for repporting, but still think this should be in forum, if it is not a bug....
Weird,  how can you be on NC18 ? Thought latest docker would be on NC 20.0.4

**Comment by timethy96** [comment] 2021-01-27 08:22
Ok thank you and sorry I will post it there...
True, this is weird. I am working on arm64 (RPI4) and directly pulling through docker-compose from ownyourbits/nextcloudpi

**Comment by ovpc** [comment] 2021-01-27 08:25
Ok, closing this for now, we can re-open if it turns out to be a bug.

**Closed by ovpc** 2021-01-27 08:25 UTC
Labels: use forums please this is not for  support

**Comment by cheesyfries7** [comment] 2021-02-05 13:26
> 
> 
> @ovpc I got it working, so no support requested.

hello, wondering how you got it working as I am encountering the same problem.

**Comment by codeclinic** [comment] 2021-02-20 12:19
> 
> 
> > @ovpc I got it working, so no support requested.
> 
> hello, wondering how you got it working as I am encountering the same problem.

ME too. I've followed all the instructions on the NCP website for Docker but get nowhere.

**Comment by wsegatto** [comment] 2021-02-24 00:33
bump

**Comment by nachoparker** [comment] 2021-02-24 02:47
make sure you use the latest image (use a tag if you want to be double sure), stop and remove all running containers and volumes.

**Comment by cheesyfries7** [comment] 2021-02-24 10:58
> 
> 
> > > @ovpc I got it working, so no support requested.
> > 
> > 
> > hello, wondering how you got it working as I am encountering the same problem.
> 
> ME too. I've followed all the instructions on the NCP website for Docker but get nowhere.

I fixed my issue by upgrading my nextcloud image via the nextcloudpi admin panel from 18 to 19, then 19 to 20. Then I was able to view the Nextcloud homepage. You can see #1256
